# Generated by Django 5.1.4 on 2026-01-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(default='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMwAAADACAMAAAB/Pny7AAAAilBMVEX...', max_length=5000),
        ),
    ]
